source 'https://github.com/CocoaPods/Specs.git'

target 'SPXDataSources', :exclusive => true do
  pod "SPXDataSources", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SPXDataSources", :path => "../"

  pod 'Kiwi'
end
